# exclude SafeMath when calculating test coverage
# https://eth-brownie.readthedocs.io/en/v1.10.3/config.html#exclude_paths
deppendencies:
    - OpenZeppelin/openzeppelin-contracts@4.6.0
compiler:
    solc:
        remappings:
            - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.6.0'
        optimizer:
            enabled: true
            runs: 200
dotenv: .env
wallets:
    from_key: ${PRIVATE_KEY}
